# Generated by Django 3.1.3 on 2020-11-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Факт', 'verbose_name_plural': 'Факты'},
        ),
        migrations.AlterField(
            model_name='fact',
            name='content',
            field=models.TextField(blank=True, verbose_name='контент'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата публикаций'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='title',
            field=models.CharField(max_length=150, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обнавлено'),
        ),
    ]
